#pragma once
#define OGPASS_WIFI_SSID "TU_WIFI_2_4_GHZ"
#define OGPASS_WIFI_PASSWORD "TU_PASSWORD_WIFI"
#define OGPASS_API_BASE "https://TU_DOMINIO_OGPASS"
#define OGPASS_READER_TOKEN "TU_TOKEN_PRIVADO_DEL_LECTOR"
// Copia la CA raíz PEM que valida el dominio. No uses setInsecure.
#define OGPASS_ROOT_CA R"PEM(-----BEGIN CERTIFICATE-----
REEMPLAZAR_POR_CA_RAIZ_PEM
-----END CERTIFICATE-----
)PEM"
