# Generated by Django 5.2.17 on 2026-09-24 20:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(max_length=160)),
                ('event', models.CharField(max_length=80)),
                ('reference', models.CharField(max_length=160)),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=160, unique=True)),
                ('kind', models.CharField(max_length=32)),
                ('actor', models.CharField(max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reversal_of', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.journal')),
            ],
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('token_hash', models.CharField(max_length=128)),
                ('active', models.BooleanField(default=True)),
                ('amount', models.PositiveIntegerField(default=1000)),
                ('cost', models.PositiveIntegerField(default=700)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('last_uid', models.CharField(blank=True, max_length=32)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='reader_positive_price'), models.CheckConstraint(condition=models.Q(('cost__lt', models.F('amount'))), name='reader_positive_margin')],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frozen', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TopUp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.UUIDField(unique=True)),
                ('amount', models.PositiveIntegerField()),
                ('status', models.CharField(default='pending', max_length=32)),
                ('payment_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('checkout_url', models.URLField(blank=True)),
                ('preference_id', models.CharField(blank=True, max_length=100)),
                ('fee', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('journal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.journal')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=32, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.UUIDField(unique=True)),
                ('uid', models.CharField(max_length=32)),
                ('amount', models.PositiveIntegerField()),
                ('cost', models.PositiveIntegerField()),
                ('status', models.CharField(default='pending', max_length=32)),
                ('reason', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('journal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.journal')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.reader')),
                ('wallet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=80)),
                ('amount', models.BigIntegerField()),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='core.journal')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('amount', 0), _negated=True), name='nonzero_entry')],
            },
        ),
        migrations.CreateModel(
            name='StellarAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(choices=[('testnet', 'Testnet'), ('mainnet', 'Mainnet')], max_length=10)),
                ('address', models.CharField(max_length=56)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.wallet')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('wallet', 'network'), name='wallet_stellar_network')],
            },
        ),
    ]
