# Generated by Django 5.2.17 on 2026-09-24 21:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_seal_journals'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='card_number',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.CreateModel(
            name='CardScan',
            fields=[
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=32)),
                ('purpose', models.CharField(choices=[('balance', 'Saldo'), ('payment', 'Pago')], default='balance', max_length=10)),
                ('pairing_hash', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('paired_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('operation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.operation')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.reader')),
                ('wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.wallet')),
            ],
        ),
    ]
