# Generated by Django 5.2.17 on 2026-09-25 02:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_tag_card_number_cardscan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.UUIDField(unique=True)),
                ('amount', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('ready', 'Por activar'), ('activated', 'Activada'), ('cancelled', 'Cancelada')], default='ready', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_preloads', to='core.wallet')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_preloads', to='core.wallet')),
                ('reserve_journal', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.journal')),
                ('settlement_journal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.journal')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='positive_preload')],
            },
        ),
        migrations.CreateModel(
            name='WalletEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.wallet')),
            ],
            options={
                'indexes': [models.Index(fields=['wallet', 'id'], name='core_wallet_wallet__880a9c_idx')],
            },
        ),
    ]
