# Generated by Django 5.2.17 on 2026-09-25 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_preload_walletevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardAssociationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=9)),
                ('status', models.CharField(default='pending', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.tag')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.wallet')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('wallet',), name='one_pending_card_request')],
            },
        ),
    ]
