# Generated by Django 5.2.17 on 2026-09-30

import django.conf
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(django.conf.settings.AUTH_USER_MODEL),
        ('core', '0007_cardassociationrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalTransitCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issuer', models.CharField(choices=[('OG', 'OGPASS'), ('RED', 'Red Movilidad'), ('SUBE', 'SUBE')], max_length=8)),
                ('encrypted_reference', models.TextField()),
                ('reference_hmac', models.CharField(max_length=64)),
                ('verification_status', models.CharField(choices=[('declared', 'Declarada'), ('verified', 'Verificada'), ('revoked', 'Revocada')], default='declared', max_length=12)),
                ('consent_version', models.CharField(max_length=48)),
                ('consented_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='external_transit_credentials', to=django.conf.settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='externaltransitcredential',
            constraint=models.UniqueConstraint(fields=('issuer', 'reference_hmac'), name='unique_external_transit_reference'),
        ),
        migrations.AddIndex(
            model_name='externaltransitcredential',
            index=models.Index(fields=['user', 'issuer', 'verification_status'], name='transit_credential_owner_idx'),
        ),
        migrations.CreateModel(
            name='ExternalTransitBalanceSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=32)),
                ('balance_amount', models.BigIntegerField(blank=True, null=True)),
                ('currency', models.CharField(max_length=3)),
                ('source', models.CharField(max_length=120)),
                ('observed_at', models.DateTimeField(blank=True, null=True)),
                ('queried_at', models.DateTimeField(auto_now_add=True)),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balance_snapshots', to='core.externaltransitcredential')),
            ],
        ),
        migrations.AddIndex(
            model_name='externaltransitbalancesnapshot',
            index=models.Index(fields=['credential', '-queried_at'], name='transit_balance_recent_idx'),
        ),
    ]
